### PR TITLE
ci: add github actions

### PR DESCRIPTION
**Pull request by ramontayag**
- run `mix test`
- run `mix dialyzer`

### CODE REVIEW

**Comment by ramontayag** [comment]
Couldn't find a way to run `mix format` but just fail the CI if there's a formatting issue. So I just added https://github.com/mhinz/vim-mix-format in my own vim config to automatically do it when I save a file.

**Comment by ramontayag** [comment]
Let me actually test this first.

**Comment by ramontayag** [comment]
Ok, passes on my fork. A bit slow, but it works.

**Review by RooSoft — APPROVED** [review]
Let's try this

**Pull request merged**
